### ISSUE TITLE
Fatal Server Crash With Life Inducer (Beta 1.7.0 Version 3.0.5)

### ISSUE THREAD

**Issue by Fang20001** [Jamezo97/CloneCraft#1]
Hey Jamezo,
It appears that when I put a lifeless egg into a Life Inducer on my server, it crashes. I cannot re-enter the world until I uninstall CloneCraft. As far as I can tell, this happens on all of the other beta versions. The server was running a large mod pack as well.
Server error report:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/30/15 5:41 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.jamezo97.clonecraft.tileentity.TileEntityLifeInducer.spawnSparks(DDD)V
	at net.jamezo97.clonecraft.tileentity.TileEntityLifeInducer.func_145842_c(TileEntityLifeInducer.java:369)
	at net.minecraft.block.BlockContainer.func_149696_a(SourceFile:29)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:968)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:955)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.jamezo97.clonecraft.tileentity.TileEntityLifeInducer.func_145842_c(TileEntityLifeInducer.java:369)
	at net.minecraft.block.BlockContainer.func_149696_a(SourceFile:29)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:968)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:955)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['FangTwoThousand'/227, l='world', x=-409.49, y=134.90, z=205.71]]
	Chunk stats: ServerChunkCache: 1026 Drop: 0
	Level seed: 2005761734631650269
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-192,64,252), Chunk: (at 0,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1860126 game time, 1460709 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55126 (now: false), thunder time: 8897 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3911134496 bytes (3729 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 2 total; -Xms4096M -Xmx4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 47 mods loaded, 47 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forgelauncher.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forgelauncher.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-stable-5} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.2.11} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-stable-5} [Applied Energistics 2] (appliedenergistics2-rv2-stable-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{7.0.8} [BuildCraft] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{7.0.8} [BC Builders] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{7.0.8} [BC Energy] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Robotics{7.0.8} [BC Robotics] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{7.0.8} [BC Silicon] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{7.0.8} [BC Transport] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{7.0.8} [BC Factory] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	clearingblock{0.3} [ClearingBlock Mod] (Clearing Block Mod-0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	clonecraft{3.0} [CloneCraft] (CloneCraft-vB3.0.5 - MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SKC-Core{1.1.2.0} [SKC Core] (SKC-Core-1.1.2.0-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SKC-CraftableHorseArmor{1.1.2.0} [Craftable Horse Armor] (CraftableHorseArmor-1.1.2.0-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.2} [MapWriter] (MapWriter-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{8.1.4} [Mekanism] (Mekanism-1.7.10-8.1.4.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{8.1.4} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.4.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{8.1.4} [MekanismTools] (MekanismTools-1.7.10-8.1.4.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-512.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.4.5.44} [ProjectRed] (ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.4.5.44} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
	AE2 Version: stable rv2-stable-5 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 10; [EntityPlayerMP['FangTwoThousand'/227, l='world', x=-409.49, y=134.90, z=205.71]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Jamezo97** [comment]
I'm not 100% sure what's going on here, as I can't make out line numbers and method names, but after getting something similar myself, I've patched it up. Looks like I was calling a Client method from the server side when I shouldn't have been.. I think.
Just about to upload a beta, it should be fixed there.
Thanks heaps :)

**Comment by Fang20001** [comment]
Np man, I love CloneCraft and am looking forward to future versions :)
