### ISSUE TITLE
can't get into a specific world

### ISSUE THREAD

**Issue by vosotheacheng** [Jamezo97/CloneCraft#20]
so i have made my own survival  world(for 1.7.10) with a bunch of mod and when i install CloneCraft i cannot get into my survival world but i can go into other world. if i log into the world i will crash. her is the crash report:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/16/16 10:50 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
	at com.pahimar.ee3.util.CommonSoundHelper.playSoundAtPlayer(CommonSoundHelper.java:27)
	at com.pahimar.ee3.util.CommonSoundHelper.playSoundAtPlayer(CommonSoundHelper.java:22)
	at com.pahimar.ee3.block.BlockAlchemyArray.func_149689_a(BlockAlchemyArray.java:228)
	at com.pahimar.ee3.item.ItemChalk.placeBlockAt(ItemChalk.java:242)
	at com.pahimar.ee3.item.ItemChalk.placeAlchemyArray(ItemChalk.java:160)
	at com.pahimar.ee3.item.ItemChalk.func_77648_a(ItemChalk.java:68)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
	at net.jamezo97.clonecraft.build.BlockItemRegistry.init2(BlockItemRegistry.java:148)
	at net.jamezo97.clonecraft.build.BlockItemRegistry.init(BlockItemRegistry.java:236)
	at net.jamezo97.clonecraft.CloneCraft.postInit(CloneCraft.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
	at com.pahimar.ee3.util.CommonSoundHelper.playSoundAtPlayer(CommonSoundHelper.java:27)
	at com.pahimar.ee3.util.CommonSoundHelper.playSoundAtPlayer(CommonSoundHelper.java:22)
	at com.pahimar.ee3.block.BlockAlchemyArray.func_149689_a(BlockAlchemyArray.java:228)
	at com.pahimar.ee3.item.ItemChalk.placeBlockAt(ItemChalk.java:242)
	at com.pahimar.ee3.item.ItemChalk.placeAlchemyArray(ItemChalk.java:160)
	at com.pahimar.ee3.item.ItemChalk.func_77648_a(ItemChalk.java:68)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
	at net.jamezo97.clonecraft.build.BlockItemRegistry.init2(BlockItemRegistry.java:148)
	at net.jamezo97.clonecraft.build.BlockItemRegistry.init(BlockItemRegistry.java:236)
	at net.jamezo97.clonecraft.CloneCraft.postInit(CloneCraft.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 707
	Entity Name: vosothea
	Entity's Exact location: 334.54, 82.00, 80.79
	Entity's Block location: World: (334,82,80), Chunk: (at 14,5,0 in 20,5; contains blocks 320,0,80 to 335,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1892)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Affected level --
Details:
	Level name: 1.7.0moddedsurvival
	All players: 1 total; [EntityPlayerMP['vosothea'/707, l='1.7.0moddedsurvival', x=334.54, y=82.00, z=80.79]]
	Chunk stats: ServerChunkCache: 779 Drop: 190
	Level seed: 3209692264629371530
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (112,64,252), Chunk: (at 0,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 645145 game time, 209815 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 22767 (now: false), thunder time: 26196 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281704856 bytes (268 MB) / 758247424 bytes (723 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAA	BattleTowers{1.4.8} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCHIJAAAA	clonecraft{3.0} [CloneCraft] (CloneCraft-vB3.0.13.-.MC1.7.10.jar) 
	UCHIJAAAA	craftnstar{0.2.1} [Craftable Nether Star +] (Craftable-Nether-Star-Mod-1.7.10.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10 (1).jar) 
	UCHIJAAAA	DynamicLights{1.3.5} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	endercompass{1.2} [Ender Compass] (Ender-Compass-Mod-1.7.10.jar) 
	UCHIJAAAA	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) 
	UCHIJAAAA	farlanders{1.2b} [The Farlanders] (Farlanders-Mod-1.7.10.jar) 
	UCHIJAAAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum-Core-Lib-1.7.10.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats.jar) 
	UCHIJAAAA	headcrumbs{1.2.5} [Headcrumbs] (Headcrumbs-Mod-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.3.91} [Inventory Pets] (inventorypets-1.7.10-1.3.91-universal.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JammyFurniture{5.0.0 [Build Smeagol]} [Jammy Furniture Mod] (Jammy-Furniture-Reborn-Mod-1.7.10.jar) 
	UCHIJAAAA	littlehelpers{1.5.1 - 1.7.10} [LittleHelpers] (LittleHelpers-1.7.10-1.5.3 (1).jar) 
	UCHIJAAAA	lootbags{1.2.0} [Loot Bags] (LootBags-1.7.10-1.2.0.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	powerinventory{2.0.0} [Overpowered Inventory] (OverpoweredInventory-1.7.10-2.0.0.jar) 
	UCHIJAAAA	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-Mod-by-grim3212-1.7.10.jar) 
	UCHIJAAAA	RottenFleshToLeather{1.7.10-2.0} [Rotten Flesh to Leather] (RottenFleshToLeather-2.1-1.7.10.jar) 
	UCHIJAAAA	dna948{3.1} [The Last Sword You Will Ever Need Mod] (The_Last_Sword_You_Will_Ever_Need_Mod-1.7.10-3.1.jar) 
	UCHIJAAAA	torchLevers{1.4.2} [Torch Levers] (TorchLevers-V1.4.2-MC1.7.10.jar) 
	UCHIJAAAA	jordy141minecraftmagicwrench{0.5 Alpha} [Magic Wrench] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	uncraftingTable{1.7.10 Alpha 1} [Uncrafting Table] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	weatherManMod{RELEASE} [Weather Carpets] (Weather Carpets Mod-1.2.5.jar) 
	UCHIJAAAA	YoutuberStructures{1.0} [Youtuber Structures] (Youtuber Structures.jar) 
	UCHIJAAAA	youtubers{1.8.0} [Youtubers+ Mod] (youtubers-1.8.0-MC1.7.10.jar) 
	UCHIJAAAA	voxelmap{1.7.10} [VoxelMap No Radar] (Zans-Minimap-No-Radar-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['vosothea'/707, l='1.7.0moddedsurvival', x=334.54, y=82.00, z=80.79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 9
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 3.1.0 - Build 9.17.10.4229
	OpenGlRenderer: Intel(R) HD Graphics 3000
	OpenGlVendor: Intel
	CpuCount: 4

HERE IS THE MOD LIST:
-Treecapicator
-battlegear 2
-Nervermin 2
-backpack
-battle tower
-codechicken core
-craftable netherstar
-damage indicator
-dynamic light
-ender compass
-equivalent exchange 3
-farlander
-gollum core'
-grim3212 core
-hat
-headcrumb
-IchunUntil
-inventory pet
-iron chest
-jammy furniture
-lootbag
-malisis core
-malisis door
-NEI
-optifine
-overpowered inventory
-pokeball
-rottenflesh to leather
-the last sword you'll ever need
-torched lever
-uncrafting table
-weather carpet
-youtuber+
-youtuber structure
-zan minimap

**Comment by vosotheacheng** [comment]
i found out it crash because i have equivalent exchange 3. my other worlds don't have any item related to equivalent exchange mod(except the recipe in NEI). can anyone help me!!!

**Comment by coolnickname** [comment]
Please use spoilers next time. And it clearly is a bug with EE3 so there you've got your problem.
But as far as I know this mod is kinda inactive so either you could ask for help at EE3 or try to replace one of the bugging mods
