### ISSUE TITLE
Crash when I try to get DNA from an Entity

### ISSUE THREAD

**Issue by Protoss3xe** [Jamezo97/CloneCraft#34]
When I use a Needle to get some DNA from any Entity (vanilla or mod) the game crashes.

In the crash log i've found this:

java.lang.NoClassDefFoundError: Could not initialize class **net.jamezo97.clonecraft.EntityColourHandler
	at net.jamezo97.clonecraft.item.ItemData.getPrimaryColour(ItemData.java:258)** ~[ItemData.class:?]
	at net.jamezo97.clonecraft.item.ItemSpawnEgg.func_77653_i(ItemSpawnEgg.java:66) ~[ItemSpawnEgg.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489) ~[add.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456) ~[bfl.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566) ~[bfl.class:?]
	at com.gildedgames.util.tab.client.TabClientEvents.tickStart(TabClientEvents.java:153) ~[TabClientEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_37_TabClientEvents_tickStart_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Protoss3xe** [comment]
[FIXED] I've renamed the mod (the jar file and the modid) to be loaded first. Clonecraft has to be the first mod file in the folder and I've put the same name to the modid
