### ISSUE TITLE
I crashed when i right-clicked the farm button

### ISSUE THREAD

**Issue by MrDiamond123** [Jamezo97/CloneCraft#8]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/16/15 5:21 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.block.BlockReed cannot be cast to net.minecraft.block.IGrowable
	at net.jamezo97.clonecraft.clone.BreakableBlocks.canBreak(BreakableBlocks.java:113)
	at net.jamezo97.clonecraft.clone.ai.block.DefaultBlockFinder.getNextBlock(DefaultBlockFinder.java:68)
	at net.jamezo97.clonecraft.clone.ai.block.EntityAIMine.selectNextBlock(EntityAIMine.java:59)
	at net.jamezo97.clonecraft.clone.ai.block.EntityAIMine.func_75250_a(EntityAIMine.java:52)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70619_bc(EntityClone.java:343)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70636_d(EntityClone.java:641)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70071_h_(EntityClone.java:420)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.jamezo97.clonecraft.clone.BreakableBlocks.canBreak(BreakableBlocks.java:113)
	at net.jamezo97.clonecraft.clone.ai.block.DefaultBlockFinder.getNextBlock(DefaultBlockFinder.java:68)
	at net.jamezo97.clonecraft.clone.ai.block.EntityAIMine.selectNextBlock(EntityAIMine.java:59)
	at net.jamezo97.clonecraft.clone.ai.block.EntityAIMine.func_75250_a(EntityAIMine.java:52)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70619_bc(EntityClone.java:343)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70636_d(EntityClone.java:641)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.jamezo97.clonecraft.clone.EntityClone.func_70071_h_(EntityClone.java:420)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: clonecraft.ccEntityClone (net.jamezo97.clonecraft.clone.EntityClone)
	Entity ID: 302725
	Entity Name: Notch
	Entity's Exact location: -147.50, 64.00, -42.50
	Entity's Block location: World: (-148,64,-43), Chunk: (at 12,4,5 in -10,-3; contains blocks -160,0,-48 to -145,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Lab
	All players: 1 total; [EntityPlayerMP['Mr_Diamond123'/137, l='Lab', x=-148.65, y=64.00, z=-44.30]]
	Chunk stats: ServerChunkCache: 509 Drop: 0
	Level seed: 30381251176187521
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 2;7,59x1,3x3,2;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (-189,4,-42), Chunk: (at 3,0,6 in -12,-3; contains blocks -192,0,-48 to -177,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 692817 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 25832 (now: false), thunder time: 120865 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 176054664 bytes (167 MB) / 620249088 bytes (591 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303 (1).jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.20} [BuildCraft] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.20} [BC Silicon] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.20} [BC Transport] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.20} [BC Builders] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.20} [BC Robotics] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.20} [BC Energy] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.20} [BC Factory] (buildcraft-7.0.20 (1).jar) 
	UCHIJAAAA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	clonecraft{3.0} [CloneCraft] (CloneCraft-vB3.0.13.-.MC1.7.10.jar) 
	UCHIJAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c (1).jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102 (1).jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218 (1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	pennyarcade{Alpha 1.2} [Penny Arcade Mod] (Penny Arcade Mod Alpha 1.2.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161 (1).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Mr_Diamond123'/137, l='Lab', x=-148.65, y=64.00, z=-44.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by coolnickname** [comment]
It seems like there is sugar cane near the clone. I think if you want it to farm you need to remove all sugarcane that is near the clone.
